# Generated by Django 4.0.4 on 2022-10-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valve',
            old_name='Body',
            new_name='body',
        ),
    ]
