# Generated by Django 4.0.4 on 2022-10-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valve', '0002_rename_body_valve_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valve',
            name='body',
        ),
        migrations.AddField(
            model_name='valve',
            name='on',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
